# ref: https://gitlab.com/semen4ik20/mentoring-august/-/blob/master/.gitlab-ci.yml
image: ubuntu:16.04

stages:
  - build
  - tests

default:
  before_script:
    - apt-get update -y
    - apt install curl zip unzip -y
    - curl -s "https://get.sdkman.io" | bash
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - sdk version
    - sdk ls java
    - sdk install java 11.0.7-open

build:
  stage: build
  #  only:
  #  - master
#  before_script:
#    - sdk install java 11.0.7-open
  script:
    - ./gradlew clean assemble

api-tests:
  stage: tests
  #  only:
  #  - master
#  before_script:

  script:
    - ./gradlew test allureReport
  artifacts:
    name: "gradle report"
    paths:
      - ./build/reports/allure-report/
