# ref: https://gitlab.com/semen4ik20/mentoring-august/-/blob/master/.gitlab-ci.yml
# https://gist.github.com/RyanHarijanto/217d62534260fd2ee63278b3c293cd10
image: ubuntu:16.04

stages:
  - build
  - tests

default:
  before_script:
    - apt-get update -y
    - apt install curl zip unzip wget -y
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt install google-chrome-stable -y
    - curl -s "https://get.sdkman.io" | bash
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - sdk version
    - sdk ls java
    - sdk install java 11.0.7-open

build:
  stage: build
  #  only:
  #  - master
#  before_script:
#    - sdk install java 11.0.7-open
  script:
    - ./gradlew clean assemble

api-tests:
  stage: tests
  #  only:
  #  - master
#  before_script:

  script:
    - ./gradlew test allureReport
  artifacts:
    name: "gradle report"
    paths:
      - ./build/reports/allure-report/
