# ref: https://gitlab.com/semen4ik20/mentoring-august/-/blob/master/.gitlab-ci.yml
image: ubuntu:16.04

stages:
  - build
  - tests

default:
  before_script:
    - curl -s "https://get.sdkman.io" | bash
    - sdk version

build:
  stage: build
  #  only:
  #  - master
  script:
    - ./gradlew clean assemble

api-tests:
  stage: tests
  #  only:
  #  - master
  script:
    - ./gradlew test allureReport
  artifacts:
    name: "gradle report"
    paths:
      - ./build/reports/allure-report/
