dist: trusty

addons:
  chrome: stable

language: java

cache:
  directories:
    - $HOME/.gradle

jdk:
  - oraclejdk8
  - openjdk11

before_install:
  - chmod +x gradlew
  - curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start --vnc --tmpfs 128

script:
  - ./gradlew clean build